languageCode = "en-us"
baseUrl = "https://blog.skouf.com/"
title = "blog.skouf.com"
theme = "skouf"
publishDir = "docs"
pygmentsUseClasses = true
pygmentsCodefences = true

[author]
  author = 'Nik Skoufis'
  profile = 'Software developer, food lover'
  image = 'image/theme/profile.jpg'

[Params]
  localeOgp = "en-us"
  description = "The blog of Nik Skoufis"
  keywords = ""
  mastodonUsername = "niksko"
  mastodonDomain = "hachyderm.io"
  github = "niksko"
#  googleanalytics = "UA-76961630-4"

# Enable tags.
[taxonomies]
  tag = "tags"
