languageCode = "en-us"
title = "blog.skouf.com"
theme = "skouf"
publishDir = "docs"
pygmentsUseClasses = true
pygmentsCodefences = true

[author]
  author = 'Nik Skoufis'
  profile = 'Software developer, hardware hacker, food lover'
  image = 'image/theme/profile.jpg'

[Params]
  localeOgp = "en-us"
  description = "The personal blog of Nik Skoufis"
  keywords = ""
  twitter = "niksko"
  github = "niksko"
  googleanalytics = "UA-76961630-4"

# Enable tags.
[taxonomies]
  tag = "tags"
