---
version: '3.7'
services:
  theme:
    image: node:12.16.1-stretch-slim
    volumes:
      - ./site/themes/skouf:/app
    working_dir: /app
    entrypoint: sh

  hugo:
    build:
      context: .
    entrypoint: hugo
    volumes:
      - ./site:/site

  local:
    build:
      context: .
    command:
      - hugo
      - server
      - --bind
      - 0.0.0.0
      - --buildDrafts
    volumes:
      - ./site:/site
    ports:
      - 1313:1313
